name: Release Entity Registry Service Docker Image

on:
  push:
    tags: ['v*']

jobs:
  release:
    uses: ./.github/workflows/service_release.yml
    with:
      service: entity-registry-service
      context: ./entity-registry-service
      dockerfile: ./entity-registry-service/Dockerfile
    secrets: inherit
