name: Release History Service Docker Image

on:
  push:
    tags: ['v*']

jobs:
  release:
    uses: ./.github/workflows/service_release.yml
    with:
      service: history-service
      context: ./history-service
      dockerfile: ./history-service/Dockerfile
    secrets: inherit
