name: Release Integration Proxy Docker Image

on:
  push:
    tags: ['v*']

jobs:
  release:
    uses: ./.github/workflows/service_release.yml
    with:
      service: integration-proxy
      context: ./integration-proxy
      dockerfile: ./integration-proxy/Dockerfile
    secrets: inherit
